config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  # resources :users do
  #   member do
  #   get :following, :followers
  #   end
  # end
  devise_scope :user do
    get 'show/:id/' => 'registrations#show', as: 'show'
    get 'show/:id/following', to: 'registrations#following', as: 'following'
    get 'show/:id/followers', to: 'registrations#followers', as: 'followers'
  end
  
  resources :relationships, only: [:create, :destroy]
  
  root 'posts#index'
  
  get '/users/:id', to: 'users#show', as: 'user'
  
  resources :posts, only: %i(new create index show destroy) do
    resources :photos, only: %i(create)
    resources :likes, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :comments
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  
         
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20] # ランダムなパスワードを作成
      user.image = auth.info.image.gsub("picture","picture?type=large") if user.provider == "facebook"
    end
  end
  
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts
    @post = Post.find_by(id: params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-outline-dark edit-profile-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless @user == current_user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "フォローをやめる", class: "btn btn-primary edit-profile-btn" %>
<% end %>

app/views/users/show.html.erb
<div class="profile-wrap">
  <div class="row">
    <div class="col-md-4 text-center">
      <%= image_tag avatar_url(@user), class: "round-img" %>
    </div>
    <div class="col-md-8">
      <div class="row">
        <h2><%= @user.name %></h2>
        <% if @user == current_user %>
          <%= link_to "プロフィールを編集", edit_user_registration_path, class: "btn btn-outline-dark edit-profile-btn" %>
          <button type="button" class="setting" data-toggle="modal" data-target="#exampleModal"></button>
        <% else %>
          <span><%= render 'follow_form' %></span>
        <% end %>
        
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">設定</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
              <div class="list-group text-center">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action" %>
                <%= link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal" %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% if @user == current_user %>
        <div class="user-row">
          <!--<p>-->
          <!--  <%= @user.email %>-->
          <!--</p>-->
          <ul>
            <li>投稿<%= @user.posts.count %>件</li>
            <li><%= link_to "フォロワー#{@user.followers.count}人", followers_path(@user) %></li>
            <li><%= link_to "#{@user.following.count}人をフォロー中", following_path(@user) %></li>
          </ul>
        </div>
        <div class="row">
          <% @user.posts.each do |post| %>
            <div class="col-md-4 photo" data-toggle="modal" data-target="#myModal-<%= post.id %>">
              <!--<%= link_to(post_path(post)) do %>-->
              <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
              <!--<% end %>-->
            </div>
          <% end %>
        </div>
        
        <% @user.posts.each do |post| %>
          <div class="modal" id="myModal-<%= post.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
              <div class="modal-content">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span class="close-btn" aria-hidden="true">&times;</span></button>
                <div class="modal-body">
                  
                  <div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
                    <div class="row post-wrap">
                      <div class="col-md-8">
                        <div class="card-left">
                          <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="card-right">
                          <div class="card-right-comment">
                            <div class="card-right-name">
                              <%= link_to user_path(post.user), class: "no-text-decoration" do %>
                                <%= image_tag avatar_url(post.user), class: "post-profile-icon" %>
                              <% end %>
                              <%= link_to user_path(post.user), class: "black-color no-text-decoration post-user-name",
                                title: post.user.name do %>
                                <strong><%= post.user.name %></strong>
                              <% end %>
                              
                              <% if post.user_id == current_user.id %>
                                <%= link_to post_path(post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
                                  <div class="delete-post-icon"></div>
                                <% end %>
                              <% end %>
                              
                            </div>
                            <div class="m-2">
                              <strong>
                                <%= post.caption %>
                              </strong>
                            </div>
                            <div class="comment-post-id">
                              <div class="m-2">
                                <div id="comment-post-<%= post.id.to_s %>">
                                  <%= render 'posts/comment_list', post: post %>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div class="row parts">
                            <div id="like-icon-post-<%= post.id.to_s %>">
                              <% if post.liked_by(current_user).present? %>
                                <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
                              <% else %>
                                <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
                              <% end %>
                            </div>
                            
                          </div>
                          
                          <div id="like-text-post-<%= post.id.to_s %>">
                            <%= render "posts/like_text", { likes: post.likes } %>
                          </div>
                          
                          <div class="post-time"><%= time_ago_in_words(post.created_at).upcase %>前</div>
                          <hr>
                          
                          <div class="row parts" id="comment-form-post-<%= post.id.to_s %>">
                            <%= form_with model: [post, Comment.new], class: "w-100" do |f| %>
                              <%= f.hidden_field :user_id, value: current_user.id %>
                              <%= f.hidden_field :post_id, value: post.id %>
                              <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                </div>
              </div>
            </div>
          </div>
        <% end %>
        
        
        
      <% end %>
    </div>
  </div>
</div>